(package "send-to-osx-grammarly"
         "0.1.0"
         "A simple plugin to sent text to Grammarly")

(website-url "https://github.com/emacs-grammarly/send-to-osx-grammarly")
(keywords "osx" "grammarly")

(package-file "send-to-osx-grammarly.el")

(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
